package com.newtoncode.app.luckymonkeyhelper.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.newtoncode.app.luckymonkeyhelper.model.LuckyMonkeyModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LUCKY_MONKEY_MODEL".
*/
public class LuckyMonkeyModelDao extends AbstractDao<LuckyMonkeyModel, Long> {

    public static final String TABLENAME = "LUCKY_MONKEY_MODEL";

    /**
     * Properties of entity LuckyMonkeyModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserNick = new Property(1, String.class, "userNick", false, "USER_NICK");
        public final static Property Money = new Property(2, Integer.class, "money", false, "MONEY");
        public final static Property CreateTime = new Property(3, Long.class, "createTime", false, "CREATE_TIME");
    }


    public LuckyMonkeyModelDao(DaoConfig config) {
        super(config);
    }
    
    public LuckyMonkeyModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LUCKY_MONKEY_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_NICK\" TEXT," + // 1: userNick
                "\"MONEY\" INTEGER," + // 2: money
                "\"CREATE_TIME\" INTEGER);"); // 3: createTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LUCKY_MONKEY_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LuckyMonkeyModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userNick = entity.getUserNick();
        if (userNick != null) {
            stmt.bindString(2, userNick);
        }
 
        Integer money = entity.getMoney();
        if (money != null) {
            stmt.bindLong(3, money);
        }
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(4, createTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LuckyMonkeyModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userNick = entity.getUserNick();
        if (userNick != null) {
            stmt.bindString(2, userNick);
        }
 
        Integer money = entity.getMoney();
        if (money != null) {
            stmt.bindLong(3, money);
        }
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(4, createTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LuckyMonkeyModel readEntity(Cursor cursor, int offset) {
        LuckyMonkeyModel entity = new LuckyMonkeyModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userNick
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // money
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LuckyMonkeyModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserNick(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMoney(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCreateTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LuckyMonkeyModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LuckyMonkeyModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LuckyMonkeyModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
